# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

executors:
  golang-1_16:
    docker:
      - image: cimg/go:1.16

orbs:
  artifactory: circleci/artifactory@1.0.0
  gotools: gotest/tools@0.0.13

commands:
  setup_goenv:
    steps:
      - run:
          name: configure go environment
          command: |
            go env -w GOPROXY="https://circleci:${ARTIFACTORY_APIKEY}@hqo.jfrog.io/artifactory/api/go/go,direct"
            go env -w GOPRIVATE="github.com/HqOapp/*"
            go env -w GONOSUMDB="github.com/HqOapp/*"
            go env -w GO111MODULE="auto"

jobs:
  build_and_push_image:
    executor: golang-1_16
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - artifactory/install
      - artifactory/docker-login:
          artifactory-key: ARTIFACTORY_APIKEY
          docker-registry: hqo-docker.jfrog.io
      - run:
          name: Build & Tag Migrate Image
          command: docker build . -t hqo-docker.jfrog.io/migrate:$CIRCLE_SHA1 -t hqo-docker.jfrog.io/migrate:latest --progress=plain
          environment:
            DOCKER_BUILDKIT: 1
      - run:
          name: Publish migrate image with commit hash tag
          command: docker push hqo-docker.jfrog.io/migrate:$CIRCLE_SHA1
      - when: # master branch
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: Publish latest migrate image
                command: docker push hqo-docker.jfrog.io/migrate:latest

workflows:
  version: 2
  build:
    jobs:
      - build_and_push_image:
          name: Build Migrate
          context: artifactory
